# ----------
# Sandboxy
# ----------

# Set your environment default: Must be either `live` or `sandbox`.
# This is the environment that your app boots with.
# By default it gets refreshed with every new request to your server.
# environment: 'live'

# Specify whether to retain your current app environment on new requests.
# If set to true, your app will only load your environment default when starting.
# Every additional switch of your environment at runtime will then not be automatically resolved to your environment default on a new request.
# retain_environment: false
