# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4e0b28be813a86fc3a1d1e0477c4923676fe18e7facadbea587f21aef1fbaa94084282265fac12c2e3a06edb6ba775beec38ba5bd4aa82fd1cdf6c30eff086d3

test:
  secret_key_base: f54b8ff9aad462876cea1072ca41197d9fd17f79a77a76499dac2c472ccbb4be303991866328461a104d0a257e85c010e4403c34d8fddf8b146cf8dc65984d31

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
