require: rubocop-rspec

AllCops:
  Exclude:
    - test/**/*
  TargetRubyVersion: 2.5

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Style/Documentation:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false
